// flow-typed signature: 55a729e4997a6919436aa1ee4a94a5bc
// flow-typed version: <<STUB>>/sweetalert_v^2.0.8/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sweetalert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sweetalert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sweetalert/dist/sweetalert.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sweetalert/dist/sweetalert.min.js' {
  declare module.exports: $Exports<'sweetalert/dist/sweetalert.min'>;
}
